#!/bin/sh

set -e

case "$1" in

  configure)
    cd /opt/droidcam/
    tar -xvf *.tar.gz
    rm -r *.tar.gz
    ./install
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

#DEBHELPER#

exit 0
