#!/bin/sh

set -e

case "$1" in
  purge|remove)
    if [ -e /opt/droidcam ]; then
      rm -rf /opt/droidcam
      rmmod v4l2loopback-dc
      rm -f /lib/modules/`uname -r`/kernel/drivers/media/video/v4l2loopback-dc.ko
      rm -f /usr/bin/droidcam
      rm -f /usr/bin/droidcam-cli
      cat /etc/modules | egrep -v "^(videodev|v4l2loopback-dc)" > /tmp/.etc.modules
      prevperm=`stat -c %a /etc/modules`
      mv /tmp/.etc.modules /etc/modules
      chmod $prevperm /etc/modules
    fi
  ;;

esac

#DEBHELPER#

exit 0
